name: Issue Autoresponse

on:
  issues:
    types: [opened]

jobs:
  auto-response:
    runs-on: ubuntu-latest

    steps:
    - uses: derekprior/add-autoresponse@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        respondableId: ${{ github.event.issue.node_id }}
        response: "Thank you for opening this issue. Please note that, as we are currently working on solutions to help face the current crisis, we do not have the capacity to responds any issues."
        author: ${{ github.event.issue.user.login }}
